<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="iamnisar812" failures="1" tests="5" name="nisarahmedqae.tests.ProductDetailsTest" time="33.115" errors="0" timestamp="2024-05-26T11:50:54 IST" skipped="1">
  <testcase classname="nisarahmedqae.tests.ProductDetailsTest" name="GetSearchedProducts" time="6.336"/>
  <system-out/>
  <testcase classname="nisarahmedqae.tests.ProductDetailsTest" name="GetProductPrice" time="5.723">
    <failure message="expected [1,48,900] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1,48,900] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at nisarahmedqae.tests.ProductDetailsTest.GetProductPrice(ProductDetailsTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- GetProductPrice -->
  <system-out/>
  <testcase classname="nisarahmedqae.tests.ProductDetailsTest" name="GetProductPrice" time="6.950"/>
  <system-out/>
  <testcase classname="nisarahmedqae.tests.ProductDetailsTest" name="GetProductPrice" time="6.271"/>
  <system-out/>
  <testcase classname="nisarahmedqae.tests.ProductDetailsTest" name="GetProductPrice" time="7.835">
    <skipped/>
  </testcase> <!-- GetProductPrice -->
  <system-out/>
</testsuite> <!-- nisarahmedqae.tests.ProductDetailsTest -->
